seed: 0
env_name: Ant-v5
epochs: 5000
gamma: 0.99
n_envs: 64 # WARNING, the following 3 values must be the same in the current impl
n_eval_envs: 64
batch_size: 64
hidden_dim: 64
eval_episodes: 16
gae_lambda: 0.95
ppo_epsilon: 0.2
learning_rate: 0.0004
generator_iterations: 32
discriminator_iterations: 1
algorithm: R3GAIL  # options: R3GAIL, BC, BC_Stochastic
log_dir: ant_runs
gamma_d: 0.001 # needed for R3GAIL
gamma_g: 0.001 # needed for R3GAIL